---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssd-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/example"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
