version: "3.2"

volumes:
  nextcloud:

services:

  # https://hub.docker.com/_/postgres
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: secret

  redis:
    image: bitnami/redis
    restart: always
    environment:
      REDIS_PASSWORD: secret

  nextcloud:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
      - redis
    restart: always
    environment:
      NEXTCLOUD_ADMIN_USER: jadams
      NEXTCLOUD_ADMIN_PASSWORD: secret
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: secret


