# This is an example .yaml of the required secrets. Uncomment and replace the VALUES with your appropriate base64 encoded string
---
apiVersion: v1
kind: Secret
metadata:
  name: db
type: Opaque
data:
  user: BASE_64_ENCODED_USER
  pass: BASE_64_ENCODED_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
type: Opaque
data:
  pass: BASE_64_ENCODED_PASSWORD
