apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
  labels:
    app: nextcloud
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
        - name: nextcloud-pv-storage
          persistentVolumeClaim:
            claimName: nextcloud-pv-claim
      containers:
        - name: nextcloud
          image: nextcloud:20
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/var/www/html"
              name: nextcloud-pv-storage
          ports:
            - containerPort: 80
          env:
            - name: NC_overwriteprotocol                                                   
              value: https
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: trusted-domains
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: user
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: pass
            - name: POSTGRES_DB
              value: nextcloud
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: pass
            - name: POSTGRES_HOST
              value: postgres
            - name: REDIS_HOST
              value: redis
            - name: REDIS_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: pass
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - name: http
      port: 8080
      targetPort: 80 
